// S&P 500 구성 종목 (2024년 기준, 시총 상위)
// 출처: S&P Dow Jones Indices (분기별 리밸런싱으로 소폭 변동 있음)
export const SP500_STOCKS: Array<{ symbol: string; name: string }> = [
  { symbol: 'AAPL', name: 'Apple Inc.' },
  { symbol: 'MSFT', name: 'Microsoft Corporation' },
  { symbol: 'NVDA', name: 'NVIDIA Corporation' },
  { symbol: 'AMZN', name: 'Amazon.com Inc.' },
  { symbol: 'GOOGL', name: 'Alphabet Inc. Class A' },
  { symbol: 'GOOG', name: 'Alphabet Inc. Class C' },
  { symbol: 'META', name: 'Meta Platforms Inc.' },
  { symbol: 'TSLA', name: 'Tesla Inc.' },
  { symbol: 'BRK-B', name: 'Berkshire Hathaway Inc.' },
  { symbol: 'JPM', name: 'JPMorgan Chase & Co.' },
  { symbol: 'LLY', name: 'Eli Lilly and Company' },
  { symbol: 'V', name: 'Visa Inc.' },
  { symbol: 'UNH', name: 'UnitedHealth Group Inc.' },
  { symbol: 'XOM', name: 'Exxon Mobil Corporation' },
  { symbol: 'MA', name: 'Mastercard Inc.' },
  { symbol: 'JNJ', name: 'Johnson & Johnson' },
  { symbol: 'PG', name: 'Procter & Gamble Co.' },
  { symbol: 'COST', name: 'Costco Wholesale Corporation' },
  { symbol: 'HD', name: 'Home Depot Inc.' },
  { symbol: 'AVGO', name: 'Broadcom Inc.' },
  { symbol: 'MRK', name: 'Merck & Co. Inc.' },
  { symbol: 'ABBV', name: 'AbbVie Inc.' },
  { symbol: 'CVX', name: 'Chevron Corporation' },
  { symbol: 'KO', name: 'Coca-Cola Company' },
  { symbol: 'PEP', name: 'PepsiCo Inc.' },
  { symbol: 'WMT', name: 'Walmart Inc.' },
  { symbol: 'ADBE', name: 'Adobe Inc.' },
  { symbol: 'AMD', name: 'Advanced Micro Devices Inc.' },
  { symbol: 'CRM', name: 'Salesforce Inc.' },
  { symbol: 'TMO', name: 'Thermo Fisher Scientific Inc.' },
  { symbol: 'ACN', name: 'Accenture plc' },
  { symbol: 'NFLX', name: 'Netflix Inc.' },
  { symbol: 'BAC', name: 'Bank of America Corp.' },
  { symbol: 'ORCL', name: 'Oracle Corporation' },
  { symbol: 'MCD', name: "McDonald's Corporation" },
  { symbol: 'LIN', name: 'Linde plc' },
  { symbol: 'ABT', name: 'Abbott Laboratories' },
  { symbol: 'PFE', name: 'Pfizer Inc.' },
  { symbol: 'DHR', name: 'Danaher Corporation' },
  { symbol: 'CSCO', name: 'Cisco Systems Inc.' },
  { symbol: 'IBM', name: 'International Business Machines' },
  { symbol: 'TXN', name: 'Texas Instruments Inc.' },
  { symbol: 'NEE', name: 'NextEra Energy Inc.' },
  { symbol: 'INTU', name: 'Intuit Inc.' },
  { symbol: 'PM', name: 'Philip Morris International' },
  { symbol: 'AMGN', name: 'Amgen Inc.' },
  { symbol: 'CMCSA', name: 'Comcast Corporation' },
  { symbol: 'INTC', name: 'Intel Corporation' },
  { symbol: 'UNP', name: 'Union Pacific Corporation' },
  { symbol: 'QCOM', name: 'Qualcomm Inc.' },
  { symbol: 'HON', name: 'Honeywell International Inc.' },
  { symbol: 'T', name: 'AT&T Inc.' },
  { symbol: 'VZ', name: 'Verizon Communications Inc.' },
  { symbol: 'SBUX', name: 'Starbucks Corporation' },
  { symbol: 'GE', name: 'GE Aerospace' },
  { symbol: 'RTX', name: 'RTX Corporation' },
  { symbol: 'LOW', name: "Lowe's Companies Inc." },
  { symbol: 'CAT', name: 'Caterpillar Inc.' },
  { symbol: 'NOW', name: 'ServiceNow Inc.' },
  { symbol: 'MS', name: 'Morgan Stanley' },
  { symbol: 'BLK', name: 'BlackRock Inc.' },
  { symbol: 'SPGI', name: 'S&P Global Inc.' },
  { symbol: 'AXP', name: 'American Express Company' },
  { symbol: 'DE', name: 'Deere & Company' },
  { symbol: 'ISRG', name: 'Intuitive Surgical Inc.' },
  { symbol: 'UPS', name: 'United Parcel Service Inc.' },
  { symbol: 'BMY', name: 'Bristol-Myers Squibb Company' },
  { symbol: 'GS', name: 'Goldman Sachs Group Inc.' },
  { symbol: 'COP', name: 'ConocoPhillips' },
  { symbol: 'PLD', name: 'Prologis Inc.' },
  { symbol: 'ADI', name: 'Analog Devices Inc.' },
  { symbol: 'SYK', name: 'Stryker Corporation' },
  { symbol: 'MDT', name: 'Medtronic plc' },
  { symbol: 'AMAT', name: 'Applied Materials Inc.' },
  { symbol: 'SCHW', name: 'Charles Schwab Corporation' },
  { symbol: 'BKNG', name: 'Booking Holdings Inc.' },
  { symbol: 'MU', name: 'Micron Technology Inc.' },
  { symbol: 'LRCX', name: 'Lam Research Corporation' },
  { symbol: 'CB', name: 'Chubb Limited' },
  { symbol: 'GILD', name: 'Gilead Sciences Inc.' },
  { symbol: 'C', name: 'Citigroup Inc.' },
  { symbol: 'SO', name: 'Southern Company' },
  { symbol: 'TJX', name: 'TJX Companies Inc.' },
  { symbol: 'ELV', name: 'Elevance Health Inc.' },
  { symbol: 'CI', name: 'Cigna Group' },
  { symbol: 'DUK', name: 'Duke Energy Corporation' },
  { symbol: 'EOG', name: 'EOG Resources Inc.' },
  { symbol: 'ITW', name: 'Illinois Tool Works Inc.' },
  { symbol: 'WFC', name: 'Wells Fargo & Company' },
  { symbol: 'PGR', name: 'Progressive Corporation' },
  { symbol: 'BSX', name: 'Boston Scientific Corporation' },
  { symbol: 'HCA', name: 'HCA Healthcare Inc.' },
  { symbol: 'AON', name: 'Aon plc' },
  { symbol: 'MMC', name: 'Marsh & McLennan Companies' },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals' },
  { symbol: 'ETN', name: 'Eaton Corporation plc' },
  { symbol: 'FI', name: 'Fiserv Inc.' },
  { symbol: 'ZTS', name: 'Zoetis Inc.' },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals Inc.' },
  { symbol: 'APH', name: 'Amphenol Corporation' },
  { symbol: 'KLAC', name: 'KLA Corporation' },
  { symbol: 'MCO', name: "Moody's Corporation" },
  { symbol: 'SLB', name: 'Schlumberger Limited' },
  { symbol: 'ADP', name: 'Automatic Data Processing Inc.' },
  { symbol: 'NSC', name: 'Norfolk Southern Corporation' },
  { symbol: 'MMM', name: '3M Company' },
  { symbol: 'PH', name: 'Parker-Hannifin Corporation' },
  { symbol: 'ECL', name: 'Ecolab Inc.' },
  { symbol: 'CME', name: 'CME Group Inc.' },
  { symbol: 'MSI', name: 'Motorola Solutions Inc.' },
  { symbol: 'MPC', name: 'Marathon Petroleum Corporation' },
  { symbol: 'TGT', name: 'Target Corporation' },
  { symbol: 'SNPS', name: 'Synopsys Inc.' },
  { symbol: 'CDNS', name: 'Cadence Design Systems Inc.' },
  { symbol: 'FDX', name: 'FedEx Corporation' },
  { symbol: 'MCK', name: 'McKesson Corporation' },
  { symbol: 'PSX', name: 'Phillips 66' },
  { symbol: 'GD', name: 'General Dynamics Corporation' },
  { symbol: 'OXY', name: 'Occidental Petroleum Corporation' },
  { symbol: 'ORLY', name: "O'Reilly Automotive Inc." },
  { symbol: 'NOC', name: 'Northrop Grumman Corporation' },
  { symbol: 'AIG', name: 'American International Group' },
  { symbol: 'WM', name: 'Waste Management Inc.' },
  { symbol: 'VLO', name: 'Valero Energy Corporation' },
  { symbol: 'EMR', name: 'Emerson Electric Co.' },
  { symbol: 'MET', name: 'MetLife Inc.' },
  { symbol: 'FCX', name: 'Freeport-McMoRan Inc.' },
  { symbol: 'CTAS', name: 'Cintas Corporation' },
  { symbol: 'CARR', name: 'Carrier Global Corporation' },
  { symbol: 'LMT', name: 'Lockheed Martin Corporation' },
  { symbol: 'D', name: 'Dominion Energy Inc.' },
  { symbol: 'PAYX', name: 'Paychex Inc.' },
  { symbol: 'MCHP', name: 'Microchip Technology Inc.' },
  { symbol: 'EW', name: 'Edwards Lifesciences Corporation' },
  { symbol: 'APD', name: 'Air Products and Chemicals Inc.' },
  { symbol: 'USB', name: 'U.S. Bancorp' },
  { symbol: 'MNST', name: 'Monster Beverage Corporation' },
  { symbol: 'ROP', name: 'Roper Technologies Inc.' },
  { symbol: 'PCAR', name: 'PACCAR Inc.' },
  { symbol: 'TFC', name: 'Truist Financial Corporation' },
  { symbol: 'A', name: 'Agilent Technologies Inc.' },
  { symbol: 'CL', name: 'Colgate-Palmolive Company' },
  { symbol: 'HLT', name: 'Hilton Worldwide Holdings Inc.' },
  { symbol: 'SPG', name: 'Simon Property Group Inc.' },
  { symbol: 'FICO', name: 'Fair Isaac Corporation' },
  { symbol: 'O', name: 'Realty Income Corporation' },
  { symbol: 'AZO', name: 'AutoZone Inc.' },
  { symbol: 'DXCM', name: 'DexCom Inc.' },
  { symbol: 'NXPI', name: 'NXP Semiconductors NV' },
  { symbol: 'CPRT', name: 'Copart Inc.' },
  { symbol: 'SHW', name: 'Sherwin-Williams Company' },
  { symbol: 'IQV', name: 'IQVIA Holdings Inc.' },
  { symbol: 'PRU', name: 'Prudential Financial Inc.' },
  { symbol: 'GWW', name: 'W.W. Grainger Inc.' },
  { symbol: 'AFL', name: 'Aflac Inc.' },
  { symbol: 'IDXX', name: 'IDEXX Laboratories Inc.' },
  { symbol: 'HSY', name: 'Hershey Company' },
  { symbol: 'ALL', name: 'Allstate Corporation' },
  { symbol: 'HES', name: 'Hess Corporation' },
  { symbol: 'AME', name: 'AMETEK Inc.' },
  { symbol: 'WELL', name: 'Welltower Inc.' },
  { symbol: 'KMB', name: 'Kimberly-Clark Corporation' },
  { symbol: 'TEL', name: 'TE Connectivity Ltd.' },
  { symbol: 'TDG', name: 'TransDigm Group Inc.' },
  { symbol: 'FAST', name: 'Fastenal Company' },
  { symbol: 'OTIS', name: 'Otis Worldwide Corporation' },
  { symbol: 'WBA', name: 'Walgreens Boots Alliance Inc.' },
  { symbol: 'CTSH', name: 'Cognizant Technology Solutions' },
  { symbol: 'EXC', name: 'Exelon Corporation' },
  { symbol: 'EA', name: 'Electronic Arts Inc.' },
  { symbol: 'MRNA', name: 'Moderna Inc.' },
  { symbol: 'BAX', name: 'Baxter International Inc.' },
  { symbol: 'GIS', name: 'General Mills Inc.' },
  { symbol: 'ACGL', name: 'Arch Capital Group Ltd.' },
  { symbol: 'BK', name: 'Bank of New York Mellon Corp.' },
  { symbol: 'PXD', name: 'Pioneer Natural Resources' },
  { symbol: 'ADSK', name: 'Autodesk Inc.' },
  { symbol: 'EL', name: 'Estee Lauder Companies Inc.' },
  { symbol: 'ROK', name: 'Rockwell Automation Inc.' },
  { symbol: 'YUM', name: 'Yum! Brands Inc.' },
  { symbol: 'FTNT', name: 'Fortinet Inc.' },
  { symbol: 'GPN', name: 'Global Payments Inc.' },
  { symbol: 'EBAY', name: 'eBay Inc.' },
  { symbol: 'WTW', name: 'Willis Towers Watson plc' },
  { symbol: 'KEYS', name: 'Keysight Technologies Inc.' },
  { symbol: 'PCG', name: 'PG&E Corporation' },
  { symbol: 'WEC', name: 'WEC Energy Group Inc.' },
  { symbol: 'ED', name: 'Consolidated Edison Inc.' },
  { symbol: 'DD', name: 'DuPont de Nemours Inc.' },
  { symbol: 'BIIB', name: 'Biogen Inc.' },
  { symbol: 'KDP', name: 'Keurig Dr Pepper Inc.' },
  { symbol: 'CTVA', name: 'Corteva Inc.' },
  { symbol: 'CDW', name: 'CDW Corporation' },
  { symbol: 'HPE', name: 'Hewlett Packard Enterprise' },
  { symbol: 'BDX', name: 'Becton Dickinson and Company' },
  { symbol: 'TROW', name: 'T. Rowe Price Group Inc.' },
  { symbol: 'ANSS', name: 'Ansys Inc.' },
  { symbol: 'MTD', name: 'Mettler-Toledo International' },
  { symbol: 'PPL', name: 'PPL Corporation' },
  { symbol: 'ALGN', name: 'Align Technology Inc.' },
  { symbol: 'DOV', name: 'Dover Corporation' },
  { symbol: 'RMD', name: 'ResMed Inc.' },
  { symbol: 'HBAN', name: 'Huntington Bancshares Inc.' },
  { symbol: 'STZ', name: 'Constellation Brands Inc.' },
  { symbol: 'MAR', name: 'Marriott International Inc.' },
  { symbol: 'VRSK', name: 'Verisk Analytics Inc.' },
  { symbol: 'LH', name: 'Laboratory Corp. of America' },
  { symbol: 'MTB', name: 'M&T Bank Corporation' },
  { symbol: 'AWK', name: 'American Water Works Company' },
  { symbol: 'BALL', name: 'Ball Corporation' },
  { symbol: 'IFF', name: 'International Flavors & Fragrances' },
  { symbol: 'GEHC', name: 'GE HealthCare Technologies Inc.' },
  { symbol: 'WAT', name: 'Waters Corporation' },
  { symbol: 'LUV', name: 'Southwest Airlines Co.' },
  { symbol: 'ES', name: 'Eversource Energy' },
  { symbol: 'DTE', name: 'DTE Energy Company' },
  { symbol: 'PPG', name: 'PPG Industries Inc.' },
  { symbol: 'AEP', name: 'American Electric Power Company' },
  { symbol: 'RF', name: 'Regions Financial Corporation' },
  { symbol: 'CFG', name: 'Citizens Financial Group Inc.' },
  { symbol: 'GLW', name: 'Corning Inc.' },
  { symbol: 'FTV', name: 'Fortive Corporation' },
  { symbol: 'CBRE', name: 'CBRE Group Inc.' },
  { symbol: 'ULTA', name: 'Ulta Beauty Inc.' },
  { symbol: 'LVS', name: 'Las Vegas Sands Corp.' },
  { symbol: 'DLTR', name: 'Dollar Tree Inc.' },
  { symbol: 'HIG', name: 'Hartford Financial Services Group' },
  { symbol: 'EFX', name: 'Equifax Inc.' },
  { symbol: 'DHI', name: 'D.R. Horton Inc.' },
  { symbol: 'STE', name: 'Steris plc' },
  { symbol: 'XEL', name: 'Xcel Energy Inc.' },
  { symbol: 'FANG', name: 'Diamondback Energy Inc.' },
  { symbol: 'TRGP', name: 'Targa Resources Corp.' },
  { symbol: 'WST', name: 'West Pharmaceutical Services' },
  { symbol: 'GPC', name: 'Genuine Parts Company' },
  { symbol: 'HAL', name: 'Halliburton Company' },
  { symbol: 'ODFL', name: 'Old Dominion Freight Line Inc.' },
  { symbol: 'KHC', name: 'Kraft Heinz Company' },
  { symbol: 'TTWO', name: 'Take-Two Interactive Software' },
  { symbol: 'AKAM', name: 'Akamai Technologies Inc.' },
  { symbol: 'WY', name: 'Weyerhaeuser Company' },
  { symbol: 'NUE', name: 'Nucor Corporation' },
  { symbol: 'STT', name: 'State Street Corporation' },
  { symbol: 'FLT', name: 'FleetCor Technologies Inc.' },
  { symbol: 'TSCO', name: 'Tractor Supply Company' },
  { symbol: 'ZBH', name: 'Zimmer Biomet Holdings Inc.' },
  { symbol: 'HPQ', name: 'HP Inc.' },
  { symbol: 'APTV', name: 'Aptiv plc' },
  { symbol: 'SYY', name: 'Sysco Corporation' },
  { symbol: 'ZBRA', name: 'Zebra Technologies Corporation' },
  { symbol: 'CINF', name: 'Cincinnati Financial Corporation' },
  { symbol: 'IP', name: 'International Paper Company' },
  { symbol: 'UAL', name: 'United Airlines Holdings Inc.' },
  { symbol: 'BR', name: 'Broadridge Financial Solutions' },
  { symbol: 'NDAQ', name: 'Nasdaq Inc.' },
  { symbol: 'MPWR', name: 'Monolithic Power Systems Inc.' },
  { symbol: 'CAH', name: 'Cardinal Health Inc.' },
  { symbol: 'ATO', name: 'Atmos Energy Corporation' },
  { symbol: 'OKE', name: 'ONEOK Inc.' },
  { symbol: 'PKG', name: 'Packaging Corp. of America' },
  { symbol: 'EIX', name: 'Edison International' },
  { symbol: 'HOLX', name: 'Hologic Inc.' },
  { symbol: 'ARES', name: 'Ares Management Corporation' },
  { symbol: 'MKC', name: 'McCormick & Company Inc.' },
  { symbol: 'SBAC', name: 'SBA Communications Corporation' },
  { symbol: 'WRB', name: 'W.R. Berkley Corporation' },
  { symbol: 'CBOE', name: 'Cboe Global Markets Inc.' },
  { symbol: 'ARE', name: 'Alexandria Real Estate Equities' },
  { symbol: 'RSG', name: 'Republic Services Inc.' },
  { symbol: 'EXPD', name: 'Expeditors International' },
  { symbol: 'WDC', name: 'Western Digital Corporation' },
  { symbol: 'DG', name: 'Dollar General Corporation' },
  { symbol: 'CTRA', name: 'Coterra Energy Inc.' },
  { symbol: 'KMI', name: 'Kinder Morgan Inc.' },
  { symbol: 'AVB', name: 'AvalonBay Communities Inc.' },
  { symbol: 'TT', name: 'Trane Technologies plc' },
  { symbol: 'PODD', name: 'Insulet Corporation' },
  { symbol: 'MAS', name: 'Masco Corporation' },
  { symbol: 'SWK', name: 'Stanley Black & Decker Inc.' },
  { symbol: 'INVH', name: 'Invitation Homes Inc.' },
  { symbol: 'LKQ', name: 'LKQ Corporation' },
  { symbol: 'NVR', name: 'NVR Inc.' },
  { symbol: 'LEN', name: 'Lennar Corporation' },
  { symbol: 'PHM', name: 'PulteGroup Inc.' },
  { symbol: 'MLM', name: 'Martin Marietta Materials' },
  { symbol: 'VMC', name: 'Vulcan Materials Company' },
  { symbol: 'COF', name: 'Capital One Financial Corp.' },
  { symbol: 'CCL', name: 'Carnival Corporation & plc' },
  { symbol: 'RCL', name: 'Royal Caribbean Cruises Ltd.' },
  { symbol: 'NCLH', name: 'Norwegian Cruise Line Holdings' },
  { symbol: 'DAL', name: 'Delta Air Lines Inc.' },
  { symbol: 'AAL', name: 'American Airlines Group Inc.' },
  { symbol: 'ALB', name: 'Albemarle Corporation' },
  { symbol: 'MHK', name: 'Mohawk Industries Inc.' },
  { symbol: 'BWA', name: 'BorgWarner Inc.' },
  { symbol: 'TPR', name: 'Tapestry Inc.' },
  { symbol: 'PVH', name: 'PVH Corp.' },
  { symbol: 'NI', name: 'NiSource Inc.' },
  { symbol: 'INCY', name: 'Incyte Corporation' },
  { symbol: 'CMS', name: 'CMS Energy Corporation' },
  { symbol: 'EVRG', name: 'Evergy Inc.' },
  { symbol: 'CNP', name: 'CenterPoint Energy Inc.' },
  { symbol: 'AES', name: 'AES Corporation' },
  { symbol: 'EQT', name: 'EQT Corporation' },
  { symbol: 'DVN', name: 'Devon Energy Corporation' },
  { symbol: 'MRO', name: 'Marathon Oil Corporation' },
  { symbol: 'APA', name: 'APA Corporation' },
  { symbol: 'CF', name: 'CF Industries Holdings Inc.' },
  { symbol: 'MOS', name: 'Mosaic Company' },
  { symbol: 'FMC', name: 'FMC Corporation' },
  { symbol: 'CE', name: 'Celanese Corporation' },
  { symbol: 'HII', name: 'Huntington Ingalls Industries' },
  { symbol: 'LW', name: 'Lamb Weston Holdings Inc.' },
  { symbol: 'CTLT', name: 'Catalent Inc.' },
  { symbol: 'TAP', name: 'Molson Coors Beverage Company' },
  { symbol: 'KR', name: 'Kroger Co.' },
  { symbol: 'CAG', name: 'Conagra Brands Inc.' },
  { symbol: 'SJM', name: 'J.M. Smucker Company' },
  { symbol: 'CPB', name: 'Campbell Soup Company' },
  { symbol: 'MKL', name: 'Markel Group Inc.' },
  { symbol: 'L', name: 'Loews Corporation' },
  { symbol: 'GL', name: 'Globe Life Inc.' },
  { symbol: 'UNM', name: 'Unum Group' },
  { symbol: 'LNC', name: 'Lincoln National Corporation' },
  { symbol: 'PFG', name: 'Principal Financial Group Inc.' },
  { symbol: 'AIZ', name: 'Assurant Inc.' },
  { symbol: 'RE', name: 'Everest Group Ltd.' },
  { symbol: 'RJF', name: 'Raymond James Financial Inc.' },
  { symbol: 'NWSA', name: 'News Corp' },
  { symbol: 'WBD', name: 'Warner Bros. Discovery Inc.' },
  { symbol: 'PARA', name: 'Paramount Global' },
  { symbol: 'FOX', name: 'Fox Corporation' },
  { symbol: 'OMC', name: 'Omnicom Group Inc.' },
  { symbol: 'IPG', name: 'Interpublic Group of Companies' },
  { symbol: 'JNPR', name: 'Juniper Networks Inc.' },
  { symbol: 'ENPH', name: 'Enphase Energy Inc.' },
  { symbol: 'SEDG', name: 'SolarEdge Technologies Inc.' },
  { symbol: 'FSLR', name: 'First Solar Inc.' },
  { symbol: 'CEG', name: 'Constellation Energy Corporation' },
  { symbol: 'VST', name: 'Vistra Corp.' },
  { symbol: 'NRG', name: 'NRG Energy Inc.' },
  { symbol: 'AEE', name: 'Ameren Corporation' },
  { symbol: 'FE', name: 'FirstEnergy Corp.' },
  { symbol: 'ETR', name: 'Entergy Corporation' },
  { symbol: 'PEG', name: 'Public Service Enterprise Group' },
  { symbol: 'SRE', name: 'Sempra' },
  { symbol: 'LNT', name: 'Alliant Energy Corporation' },
  { symbol: 'WTRG', name: 'Essential Utilities Inc.' },
  { symbol: 'SWX', name: 'Southwest Gas Holdings Inc.' },
  { symbol: 'OGE', name: 'OGE Energy Corp.' },
  { symbol: 'PINC', name: 'Premier Inc.' },
  { symbol: 'HRL', name: 'Hormel Foods Corporation' },
  { symbol: 'K', name: "Kellanova (Kellogg's)" },
  { symbol: 'CHD', name: 'Church & Dwight Co. Inc.' },
  { symbol: 'CLX', name: 'Clorox Company' },
  { symbol: 'EPC', name: 'Edgewell Personal Care Company' },
  { symbol: 'SPB', name: 'Spectrum Brands Holdings Inc.' },
  { symbol: 'DPZ', name: "Domino's Pizza Inc." },
  { symbol: 'CMG', name: 'Chipotle Mexican Grill Inc.' },
  { symbol: 'QSR', name: 'Restaurant Brands International' },
  { symbol: 'EAT', name: 'Brinker International Inc.' },
  { symbol: 'DRI', name: 'Darden Restaurants Inc.' },
  { symbol: 'BLDR', name: 'Builders FirstSource Inc.' },
  { symbol: 'TOL', name: 'Toll Brothers Inc.' },
  { symbol: 'MDU', name: 'MDU Resources Group Inc.' },
  { symbol: 'AGR', name: 'Avangrid Inc.' },
  { symbol: 'BXP', name: 'BXP Inc.' },
  { symbol: 'CPT', name: 'Camden Property Trust' },
  { symbol: 'EQR', name: 'Equity Residential' },
  { symbol: 'ESS', name: 'Essex Property Trust Inc.' },
  { symbol: 'MAA', name: 'Mid-America Apartment Communities' },
  { symbol: 'UDR', name: 'UDR Inc.' },
  { symbol: 'AMT', name: 'American Tower Corporation' },
  { symbol: 'CCI', name: 'Crown Castle Inc.' },
  { symbol: 'DLR', name: 'Digital Realty Trust Inc.' },
  { symbol: 'EQIX', name: 'Equinix Inc.' },
  { symbol: 'IRM', name: 'Iron Mountain Inc.' },
  { symbol: 'PSA', name: 'Public Storage' },
  { symbol: 'EXR', name: 'Extra Space Storage Inc.' },
  { symbol: 'LSI', name: 'Life Storage Inc.' },
  { symbol: 'CUBE', name: 'CubeSmart' },
  { symbol: 'NSA', name: 'National Storage Affiliates Trust' },
  { symbol: 'VICI', name: 'VICI Properties Inc.' },
  { symbol: 'GLPI', name: 'Gaming and Leisure Properties' },
  { symbol: 'MGM', name: 'MGM Resorts International' },
  { symbol: 'WYNN', name: 'Wynn Resorts Limited' },
  { symbol: 'HAS', name: 'Hasbro Inc.' },
  { symbol: 'MAT', name: 'Mattel Inc.' },
  { symbol: 'NKE', name: 'Nike Inc.' },
  { symbol: 'VFC', name: 'V.F. Corporation' },
  { symbol: 'HBI', name: 'Hanesbrands Inc.' },
  { symbol: 'PVH', name: 'PVH Corp.' },
  { symbol: 'RL', name: 'Ralph Lauren Corporation' },
  { symbol: 'ETSY', name: 'Etsy Inc.' },
  { symbol: 'W', name: 'Wayfair Inc.' },
  { symbol: 'LYFT', name: 'Lyft Inc.' },
  { symbol: 'UBER', name: 'Uber Technologies Inc.' },
  { symbol: 'ABNB', name: 'Airbnb Inc.' },
  { symbol: 'DASH', name: 'DoorDash Inc.' },
  { symbol: 'PINS', name: 'Pinterest Inc.' },
  { symbol: 'SNAP', name: 'Snap Inc.' },
  { symbol: 'MTCH', name: 'Match Group Inc.' },
  { symbol: 'IAC', name: 'IAC Inc.' },
  { symbol: 'Z', name: 'Zillow Group Inc.' },
  { symbol: 'OPEN', name: 'Opendoor Technologies Inc.' },
  { symbol: 'RDFN', name: 'Redfin Corporation' },
  { symbol: 'COIN', name: 'Coinbase Global Inc.' },
  { symbol: 'HOOD', name: 'Robinhood Markets Inc.' },
  { symbol: 'SOFI', name: 'SoFi Technologies Inc.' },
  { symbol: 'AFRM', name: 'Affirm Holdings Inc.' },
  { symbol: 'UPST', name: 'Upstart Holdings Inc.' },
  { symbol: 'LC', name: 'LendingClub Corporation' },
  { symbol: 'SQ', name: 'Block Inc.' },
  { symbol: 'PYPL', name: 'PayPal Holdings Inc.' },
  { symbol: 'FISV', name: 'Fiserv Inc.' },
  { symbol: 'WEX', name: 'WEX Inc.' },
  { symbol: 'GWRE', name: 'Guidewire Software Inc.' },
  { symbol: 'HUBS', name: 'HubSpot Inc.' },
  { symbol: 'DDOG', name: 'Datadog Inc.' },
  { symbol: 'NET', name: 'Cloudflare Inc.' },
  { symbol: 'SNOW', name: 'Snowflake Inc.' },
  { symbol: 'MDB', name: 'MongoDB Inc.' },
  { symbol: 'CRWD', name: 'CrowdStrike Holdings Inc.' },
  { symbol: 'S', name: 'SentinelOne Inc.' },
  { symbol: 'ZS', name: 'Zscaler Inc.' },
  { symbol: 'OKTA', name: 'Okta Inc.' },
  { symbol: 'PANW', name: 'Palo Alto Networks Inc.' },
  { symbol: 'CYBR', name: 'CyberArk Software Ltd.' },
  { symbol: 'TENB', name: 'Tenable Holdings Inc.' },
  { symbol: 'RPM', name: 'RPM International Inc.' },
  { symbol: 'FDS', name: 'FactSet Research Systems Inc.' },
  { symbol: 'MSCI', name: 'MSCI Inc.' },
  { symbol: 'ICE', name: 'Intercontinental Exchange Inc.' },
  { symbol: 'CBOE', name: 'Cboe Global Markets Inc.' },
  { symbol: 'TRV', name: 'Travelers Companies Inc.' },
  { symbol: 'PNC', name: 'PNC Financial Services Group' },
  { symbol: 'FRC', name: 'First Republic Bank' },
  { symbol: 'KEY', name: 'KeyCorp' },
  { symbol: 'FITB', name: 'Fifth Third Bancorp' },
  { symbol: 'CMA', name: 'Comerica Inc.' },
  { symbol: 'ZION', name: 'Zions Bancorporation' },
  { symbol: 'SIVB', name: 'SVB Financial Group' },
  { symbol: 'WAL', name: 'Western Alliance Bancorporation' },
  { symbol: 'PACW', name: 'PacWest Bancorp' },
  { symbol: 'OFG', name: 'OFG Bancorp' },
  { symbol: 'COLB', name: 'Columbia Banking System Inc.' },
  { symbol: 'EWBC', name: 'East West Bancorp Inc.' },
  { symbol: 'BOKF', name: 'BOK Financial Corporation' },
  { symbol: 'UMBF', name: 'UMB Financial Corporation' },
  { symbol: 'GBCI', name: 'Glacier Bancorp Inc.' },
  { symbol: 'IBOC', name: 'International Bancshares Corp.' },
  { symbol: 'PRGS', name: 'Progress Software Corporation' },
  { symbol: 'JKHY', name: 'Jack Henry & Associates Inc.' },
  { symbol: 'WU', name: 'Western Union Company' },
  { symbol: 'EG', name: 'Everest Group Ltd.' },
  { symbol: 'ERIE', name: 'Erie Indemnity Company' },
  { symbol: 'RLI', name: 'RLI Corp.' },
  { symbol: 'THG', name: 'Hanover Insurance Group Inc.' },
  { symbol: 'KMPR', name: 'Kemper Corporation' },
  { symbol: 'SIGI', name: 'Selective Insurance Group Inc.' },
  { symbol: 'NYCB', name: 'New York Community Bancorp' },
  { symbol: 'FNF', name: 'Fidelity National Financial' },
  { symbol: 'FAF', name: 'First American Financial Corp.' },
  { symbol: 'SFM', name: 'Sprouts Farmers Market Inc.' },
  { symbol: 'GFF', name: 'Griffon Corporation' },
  { symbol: 'ALLE', name: 'Allegion plc' },
  { symbol: 'JBHT', name: 'J.B. Hunt Transport Services' },
  { symbol: 'CHRW', name: 'C.H. Robinson Worldwide Inc.' },
  { symbol: 'LSTR', name: 'Landstar System Inc.' },
  { symbol: 'SAIA', name: 'Saia Inc.' },
  { symbol: 'XPO', name: 'XPO Inc.' },
  { symbol: 'WERN', name: 'Werner Enterprises Inc.' },
  { symbol: 'HTLD', name: 'Heartland Express Inc.' },
  { symbol: 'USX', name: 'U.S. Steel Corporation' },
  { symbol: 'RS', name: 'Reliance Steel & Aluminum Co.' },
  { symbol: 'STLD', name: 'Steel Dynamics Inc.' },
  { symbol: 'CMC', name: 'Commercial Metals Company' },
  { symbol: 'CENX', name: 'Century Aluminum Company' },
  { symbol: 'ATI', name: 'ATI Inc.' },
  { symbol: 'CRS', name: 'Carpenter Technology Corporation' },
  { symbol: 'EMN', name: 'Eastman Chemical Company' },
  { symbol: 'ASH', name: 'Ashland Inc.' },
  { symbol: 'RPM', name: 'RPM International Inc.' },
  { symbol: 'AVNT', name: 'Avient Corporation' },
  { symbol: 'HUN', name: 'Huntsman Corporation' },
  { symbol: 'OLN', name: 'Olin Corporation' },
  { symbol: 'TREX', name: 'Trex Company Inc.' },
  { symbol: 'AZEK', name: 'AZEK Company Inc.' },
  { symbol: 'BECN', name: 'Beacon Roofing Supply Inc.' },
  { symbol: 'IBP', name: 'Installed Building Products Inc.' },
];
